### ISSUE TITLE
Ubuntu binary release (Indigo)

### ISSUE THREAD

**Issue by 130s** [RobotnikAutomation/agvs#2]
This is a friendly request for releasing this package as Ubuntu binary (DEB, the ones that can be installed via apt-get). 
I confirmed that it compiles (with hack https://github.com/RobotnikAutomation/agvs/pull/1).
Releasing this package suite also requires https://github.com/RobotnikAutomation/robotnik_msgs to be released in advance.

It can be done by following the tutorial http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

If you're too busy I can help you out.

**Comment by RomanRobotnik** [comment]
Thanks for your interest and help.

Actually, I wan to create the release but I haven't found the moment yet xD. 

I fact, we've moved this repo to new ones, splitting the simulation part from the common:

https://github.com/RobotnikAutomation/agvs_sim.git
https://github.com/RobotnikAutomation/agvs_common.git

I'll try to do it soon.

Regards

**Comment by 130s** [comment]
Good to know about the split! And I saw you've already started working on release https://github.com/ros/rosdistro/pull/8936. Thanks!

**Comment by RomanRobotnik** [comment]
Thank you too ;)
